TestDelivery.UI/ViewModels/Questions/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestDelivery.DAL.Questions;

namespace TestDelivery.UI.ViewModels
{
    public class EditViewModel
    {
        public Question Question { get; set; }
        public string ViewPath { get; set; }
        public bool IsNew { get; set; }
    }
}

TestDelivery.UI/ViewModels/Questions/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestDelivery.DAL.Questions;

namespace TestDelivery.UI.ViewModels.Questions
{
    public class IndexViewModel
    {
        public IEnumerable<string> NewQuestionControllerNames { get; set; }
    }
}

TestDelivery.UI/ViewModels/Templates/EditQuestionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestDelivery.DAL;
using TestDelivery.DAL.Questions;

namespace TestDelivery.UI.ViewModels.Templates
{
    public class EditQuestionViewModel
    {
        public TestTemplate Template { get; set; }
        public Question Question { get; set; }
        public string ViewPath { get; set; }
    }
}

TestDelivery.UI/Controllers/Admin/Questions/FreeTextQuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestDelivery.DAL.Questions;

namespace TestDelivery.UI.Controllers
{
    public class FreeTextQuestionController : QuestionController<FreeTextQuestion>
    {

    }
}

TestDelivery.UI/Controllers/Admin/Questions/MultipleChoiceQuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestDelivery.DAL.Questions;
using TestDelivery.ServiceLayer;

namespace TestDelivery.UI.Controllers
{
    public class MultipleChoiceQuestionController : QuestionController<MultipleChoiceQuestion>
    {

    }
}

TestDelivery.UI/Controllers/Admin/Questions/ProblemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestDelivery.DAL.Questions;
using TestDelivery.ServiceLayer;

namespace TestDelivery.UI.Controllers
{
    public class ProblemController : QuestionController<Problem>
    {

    }
}

TestDelivery.UI/Controllers/Admin/Questions/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestDelivery.DAL.Questions;
using TestDelivery.ServiceLayer;
using TestDelivery.ServiceLayer.Models;
using TestDelivery.UI.Helpers;
using TestDelivery.UI.ViewModels;

namespace TestDelivery.UI.Controllers
{
    public abstract class QuestionController<T> : AdminController
        where T : Question, new()
    {
        public IQuestionService QuestionService { get; set; }
        public ITemplateService TemplateService { get; set; }
        public IQuestionViewService QuestionViewService { get; set; }

        public virtual ActionResult New()
        {
            var question = new T();
            return View("~/Views/Questions/Edit.cshtml", new EditViewModel
            {
                Question = question,
                ViewPath = QuestionViewService.GetEditPartialViewPath(question),
                IsNew = true
            });
        }

        [HttpPost]
        public virtual ActionResult Save(T problem)
        {
            return SaveQuestion(problem);
        }

        [HttpGet]
        public virtual ActionResult NewTemplateQuestion(Guid templateId)
        {
            return NewTemplateQuestion(templateId, new T());
        }

        [HttpPost]
        [ValidateInput(false)]
        public virtual ActionResult SaveTemplateQuestion(Guid templateId, [Bind(Prefix = "editQuestion")] T editedQuestion)
        {
            return TrySaveTemplateQuestion(templateId, editedQuestion);
        }

        protected ActionResult SaveQuestion(Question q)
        {
            if (q.IsNewQuestion)
                QuestionService.AddQuestion(q);
            else
                QuestionService.SaveQuestion(q);

            return RedirectToAction("Index", "Questions");
        }

        protected ActionResult TrySaveTemplateQuestion(Guid templateId, T editedQuestion)
        {
            try
            {
                DoSaveTemlateQuestion(templateId, editedQuestion);
                return Json(true);
            }
            catch
            {
                return Json(false);
            }
        }

        protected void DoSaveTemlateQuestion(Guid templateId, T editedQuestion)
        {
            var templateInfo = TemplateService.GetExtraInfo(templateId);
            var template = templateInfo.Template;
            var oldQuestion = (T)template.GetQuestion(editedQuestion.Id);
            UpdateQuestion(templateInfo, editedQuestion, oldQuestion);
            template.SaveQuestion(editedQuestion);
            TemplateService.SaveTemplate(template);
        }

        protected virtual void UpdateQuestion(TestTemplateExtraInfo templateInfo, T editedQuestion, T oldQuestion)
        {
            if (!templateInfo.CanEdit)
            {
                editedQuestion.Score = oldQuestion.Score;
            }
        }

        protected ActionResult NewTemplateQuestion(Guid templateId, Question question)
        {
            var template = TemplateService.GetTemplateById(templateId);

            question.Id = Guid.NewGuid();
            question.Summary = "New question";

            template.Questions.Add(question);
            TemplateService.SaveTemplate(template);

            return Json(new { questionId = question.Id, templateId = template.Id }, JsonRequestBehavior.AllowGet);
        }
    }
}

TestDelivery.UI/Controllers/Admin/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestDelivery.DAL;
using TestDelivery.DAL.Questions;
using TestDelivery.ServiceLayer;
using TestDelivery.ServiceLayer.Lists;
using TestDelivery.UI.Helpers;
using TestDelivery.UI.ViewModels;
using TestDelivery.UI.ViewModels.Questions;

namespace TestDelivery.UI.Controllers
{   
    public class QuestionsController : AdminController
    {
        public IQuestionService QuestionService { get; set; }
        public IQuestionViewService QuestionViewService { get; set; }

        public ActionResult Index()
        {
            return View(new IndexViewModel
            {
                NewQuestionControllerNames = QuestionViewService.GetQuestionControllerNames()
            });
        }

        public ActionResult DeleteQuestion(string id)
        {
            QuestionService.DeleteQuestion(Guid.Parse(id));
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid id)
        {
            Question question = QuestionService.GetQuestionById(id);

            return View(new EditViewModel()
            {
                Question = question,
                ViewPath = QuestionViewService.GetEditPartialViewPath(question)
            });
        }
      
        public ActionResult GetTemplateQuestions(PageInfo pageInfo)
        {
            var model = QuestionService.GetQuestions(pageInfo);
            return View(model);
        }

        public ActionResult GetQuestions(PageInfo pageInfo)
        {
            var model = QuestionService.GetQuestions(pageInfo);
            return View(model);
        }
    }
}

TestDelivery.UI/Controllers/Admin/TemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestDelivery.DAL;
using TestDelivery.DAL.Questions;
using TestDelivery.ServiceLayer;
using TestDelivery.ServiceLayer.Models;
using TestDelivery.UI.Helpers;
using TestDelivery.UI.ViewModels;
using TestDelivery.UI.ViewModels.Templates;

namespace TestDelivery.UI.Controllers
{
    public class TemplateController : AdminController
    {
        public ITemplateService TemplateService { get; set; }
        public IQuestionService QuestionService { get; set; }
        public IQuestionViewService QuestionViewService { get; set; }

        public ActionResult Index()
        {
            List<TestTemplate> list = TemplateService.ListTemplates();
            return View(list);
        }

        public ActionResult Delete(string id)
        {
            TemplateService.DeleteTemplate(Guid.Parse(id));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            return View(new EditTemplateViewModel
            {
                Info = TemplateService.GetExtraInfo(id),
                NewQuestionControllerNames = QuestionViewService.GetQuestionControllerNames()
            });
        }

        [HttpPost]
        public ActionResult New(string name)
        {
            var template = new TestTemplate()
            {
                Name = name
            };

            TemplateService.AddTemplate(template);

            return RedirectToAction("Edit", new { id = template.Id });
        }

        [HttpPost]
        public ActionResult Save(TestTemplate template, string QuestionIds)
        {
            template.Questions = GetTemplateQuestionsFromIds(template, QuestionIds);

            if (template.IsNew)
            {
                TemplateService.AddTemplate(template);
            }
            else
            {
                TemplateService.SaveTemplate(template);
            }

            return RedirectToAction("Edit", new { id = template.Id });
        }

        private List<Question> GetTemplateQuestionsFromIds(TestTemplate template, string QuestionIds)
        {
            TestTemplate oldTemplate = null;
            if (!template.IsNew)
                oldTemplate = TemplateService.GetTemplateById(template.Id);

            return QuestionIds.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                            .Select(str => str.StartsWith("@") ?
                                            oldTemplate.GetQuestion(new Guid(str.Substring(1))) :
                                            QuestionService.GetQuestionById(new Guid(str)))
                            .ToList();
        }

        public ActionResult DeleteTests(string id)
        {

            return null;
        }

        [HttpGet]
        public ActionResult EditQuestion(Guid id, Guid questionId)
        {
            var template = TemplateService.GetTemplateById(id);
            var question = template.GetQuestion(questionId);

            return View(new EditQuestionViewModel
            {
                Question = question,
                Template = template,
                ViewPath = QuestionViewService.GetEditPartialViewPath(question)
            });
        }

        [HttpGet]
        public ActionResult Questions(Guid id)
        {
            var template = TemplateService.GetTemplateById(id);
            return View(template.Questions);
        }

        public ActionResult Question(Guid id, Guid questionId)
        {
            var template = TemplateService.GetTemplateById(id);
            var question = template.GetQuestion(questionId);
            return View(question);
        }

        public ActionResult Copy(Guid id)
        {
            var toCopy = TemplateService.GetTemplateById(id);
            if (toCopy == null)
                return null;

            var copy = TemplateService.CopyTemplate(toCopy);

            return RedirectToAction("Edit", new { id = copy.Id });
        }
    }
}

TestDelivery.UI/Views/Template/Edit.cshtml
@model TestDelivery.UI.ViewModels.Templates.EditTemplateViewModel
@{
    ViewBag.Title = Model.Template.Name;
}

@if (!Model.CanEdit)
{
    <style type="text/css">
        .selected-questions .options {
            display: none;
        }
    </style>
}

<h2></h2>

<form class="js-template-form" action="@Url.Action("Save", "Template")" method="post">
    <div class="intro">
        @Html.Partial("Name", Model.Template)

        @if (!Model.CanEdit)
        {
            <p>
                Theare are some parts of this template that you can't edit, because it's in
                use.
            </p>
            <p>
                To edit all parts of the template you can
                <a>delete all tests</a>
                or
                @Html.ActionLink("crate a copy", "Copy", new { id = Model.Template.Id })
                .
            </p>
        }
    </div>

    <div id="tabs" class="free-tabs">
        <ul>
            <li><a href="#tabs-1">General</a></li>
            <li><a href="#tabs-2">Instructions</a></li>
            <li><a href="#tabs-3">Questions</a></li>
        </ul>

        <div id="tabs-1">
            @Html.Partial("General", Model.Template)
        </div>

        <div id="tabs-2">
            @Html.Partial("Instructions", Model.Template)
        </div>
        <div id="tabs-3">
            <div class="question-selector-container">
                <div class="question-selector">
                    <div class="selected-questions-section">
                        @if (Model.CanEdit)
                        {
                            <p>
                                Add questions by using the buttons below. Drag questions to reorder.
                            </p>
                            <div class="add-commands">
                                @foreach (var controllerName in Model.NewQuestionControllerNames)
                                {
                                    <button type="button" onclick="createNewTemplateQuestion('@Url.Action("NewTemplateQuestion", controllerName, new { templateId = Model.Template.Id })');">
                                        Add @controllerName
                                    </button>
                                }
                            </div>
                        }
                        else
                        {
                            <p class="attention">
                                You can't add or delete questions. You can only reorder and edit them.
                            </p>
                        }
                        <div class="selected-questions list" data-url="@Url.Action("Question", "Template", new { id = Model.Template.Id, questionId = "****" })">
                            @Html.Partial("Questions", Model.Template.Questions)
                        </div>
                    </div>
                    <div class="edit-question-container" data-url="@Url.Action("EditQuestion", "Template", new { id = Model.Template.Id, questionId = "****" })">
                    </div>
                </div>
            </div>
            <input type="hidden" name="QuestionIds" />
        </div>
    </div>
    @Html.ValidationSummary()
    <input type="submit" value="Save" />
</form>
@section scripts{
    @Scripts.Render("~/Scripts/CreateTemplate.js")
    <script type="text/javascript">
        var questionsUrl = "@Url.Action("GetTemplateQuestions", "Questions")";
        $(function () {
            initCreateTemplatePage(@Json.Encode(Model.CanEdit));
        })
    </script>
}

TestDelivery.UI/Views/Template/EditQuestion.cshtml
@model TestDelivery.UI.ViewModels.Templates.EditQuestionViewModel
@{
    Layout = null;
    var questionType = Model.Question.GetType().Name;
    ViewData.TemplateInfo.HtmlFieldPrefix = "editQuestion";    
}

<div class="edit-question-form" data-url="@Url.Action("SaveTemplateQuestion", Model.Question.GetType().Name, new { templateId = Model.Template.Id })">
    @Html.Partial(Model.ViewPath, Model.Question)

    <p>
        @{var submitAction = "saveTemplateQuestion(this, " + questionType + ".onSave);"; }
        <input type="button" class="submit" value="Save Question" onclick="@submitAction" />
    </p>
</div>

TestDelivery.UI/Views/Template/General.cshtml
@model TestDelivery.DAL.TestTemplate

@Html.HiddenFor(m => m.Id)

<div class="editor-label">
    @Html.LabelFor(model => model.TimeLimit)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.TimeLimit)
    @Html.ValidationMessageFor(model => model.TimeLimit)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.IsQuestionTimeLimitEnforced)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.IsQuestionTimeLimitEnforced)
    @Html.ValidationMessageFor(model => model.IsQuestionTimeLimitEnforced)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.IsRandomOrder)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.IsRandomOrder)
    @Html.ValidationMessageFor(model => model.IsRandomOrder)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.IsActive)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.IsActive)
    @Html.ValidationMessageFor(model => model.IsActive)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.Priority)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.Priority)
    @Html.ValidationMessageFor(model => model.Priority)
</div>

TestDelivery.UI/Views/Template/Index.cshtml
@model List<TestDelivery.DAL.TestTemplate>

@{
    ViewBag.Title = "Index";
}

<h2>Test templates</h2>

@Html.Partial("New", new TestDelivery.DAL.TestTemplate())

<div id="count" class="list" data-count="@Model.Count">

    @{
        foreach (var template in Model)
        {

            var activeClass = template.IsActive ? string.Empty : " inactive";
            
        <div class="item bottom-separator @activeClass">

            <a target="_self" href="@Url.Action("Edit", "Template", new { id = template.Id })">
                @template.Name
            </a>

            <div class="details">
                <div class="property">
                    <label>Priority </label>
                    <span>@template.Priority</span>
                </div>
                <div class="property">
                    <label>Questions </label>
                    <span>@template.Questions.Count</span>
                </div>
                <div class="property">
                    <label>Max Duration </label>
                    <span>@template.MaxDuration.ToDurationString()</span>
                </div>
            </div>

            <span class="options">
                <a href="#" onclick="deleteItem('@Url.Action("Delete", "Template", new { id = template.Id })'); return false;">
                    Delete</a>
            </span>
        </div>
        }
    }
</div>

@section scripts
{
    @Scripts.Render("~/Scripts/Templates.js")
}

TestDelivery.UI/Views/Template/Instructions.cshtml
@model TestDelivery.DAL.TestTemplate

<div class="editor-label">
    @Html.LabelFor(model => model.StartInstructions)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.StartInstructions)
    @Html.ValidationMessageFor(model => model.StartInstructions)
    <div class="js-markdown-preview"></div>
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.EndInstructions)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.EndInstructions)
    @Html.ValidationMessageFor(model => model.EndInstructions)
    <div class="js-markdown-preview"></div>
</div>

TestDelivery.UI/Views/Template/Name.cshtml
@model TestDelivery.DAL.TestTemplate
<div class="editor-field header-field">
    @Html.EditorFor(model => model.Name)
    @Html.ValidationMessageFor(model => model.Name)
</div>

TestDelivery.UI/Views/Template/New.cshtml
@model TestDelivery.DAL.TestTemplate

<div class="new-template-button">
    <input type="button" value="New template" onclick="startNewTemplate();" />
</div>
<div class="new-template-form" style="display:none;">
    @using (Html.BeginForm("New", "Template"))
    {
        @Html.ValidationSummary()
        <div class="editor-label">
            @Html.LabelFor(m => m.Name, "Template name")
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.Name)
        </div>
        <input type="submit" value="Add" />
        <input type="button" value="Cancel" onclick="cancelNewTemplate();" />
    }
</div>

TestDelivery.UI/Views/Template/Question.cshtml
@model TestDelivery.DAL.Questions.Question
@{
    Layout = null;
}

<div class="question item" data-question-id="@Model.Id">
    <span class="options">
        <a href="#" class="delete" onclick="deleteQuestion(this); return false;">Delete</a>
    </span>

    <span><a href="#" onclick="editQuestionInPlace(this); return false;">@Model.Summary</a></span>

    <div class="details">
        <div class="property">
            <span>@Model.Score p</span>
        </div>
        <div class="property">
            <span>
                @if (Model.TimeLimit > 0)
                {
                    @:@Model.Duration.ToDurationString(true)      
                }
                else
                {
                    @:No time limit
                }
            </span>
        </div>
        <div class="property">
            <span>@Model.GetType().Name</span>
        </div>
    </div>
</div>

TestDelivery.UI/Views/Template/Questions.cshtml
@model System.Collections.Generic.List<TestDelivery.DAL.Questions.Question>
@{   
    Layout = null;
}

@foreach (var q in Model)
{
    @Html.Partial("~/Views/Template/Question.cshtml", q)
}