TestDelivery.UI/ViewModels/Questions/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestDelivery.DAL.Questions;

namespace TestDelivery.UI.ViewModels
{
    public class EditViewModel
    {
        public Question Question { get; set; }
        public string ViewPath { get; set; }
        public bool IsNew { get; set; }
    }
}

TestDelivery.UI/Controllers/Admin/RespondentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestDelivery.DAL;
using TestDelivery.ServiceLayer;
using TestDelivery.UI.ViewModels;
using TestDelivery.UI.ViewModels.RespondentVM;

namespace TestDelivery.UI.Controllers
{
    public class RespondentController : AdminController
    {
        public IRespondentService RespondentService { get; set; }
        public ITemplateService TemplateService { get; set; }
        public ITestService TestService { get; set; }

        public ActionResult Index()
        {
            List<RespondentListItem> list = new List<RespondentListItem>();
            List<Respondent> respondents = GetSortedRespondents();
            foreach (var respondent in respondents)
            {
                list.Add(new RespondentListItem
                {
                    Respondent = respondent,
                    ExtraInfo = GetExtraInfo(respondent.Id)
                });
            }

            return View(list);
        }

        private List<Respondent> GetSortedRespondents()
        {
            List<Respondent> list = RespondentService.ListRespondents();
            List<Respondent> respondents = new List<Respondent>();
            respondents.AddRange(list.Where(t => !t.Tests.Any()));
            list.RemoveAll(t => !t.Tests.Any());
            respondents.AddRange(list.Where(t => t.Tests.Where(x => x.DateStarted != null && x.DateCompleted == null).Any()));
            list.RemoveAll(t => t.Tests.Where(x => x.DateStarted != null && x.DateCompleted == null).Any());
            respondents.AddRange(list.Where(t => t.Tests.Where(x => x.DateCompleted != null && x.DateEvaluated == null).Any()));
            list.RemoveAll(t => t.Tests.Where(x => x.DateCompleted != null && x.DateEvaluated == null).Any());
            list = list.OrderByDescending(t => t.Tests.Select(x => x.ScorePercent).Sum() / t.Tests.Count()).ToList();
            respondents.AddRange(list);
            return respondents;
        }

        public ActionResult New(Respondent respondent)
        {
            ModelState.Clear();
            return View(respondent);
        }

        public ActionResult Save(Respondent respondent)
        {
            if (!ModelState.IsValid) return View("New", respondent);
            var added = false;
            if (respondent.Id == Guid.Empty)
            {
                var exists = RespondentService.ListRespondents().Where(r => r.Email == respondent.Email).Any();
                if (exists) ModelState.AddModelError(String.Empty, "The email is already in use");
                else
                {
                    RespondentService.AddRespondent(respondent);
                    added = true;
                }
            }
            else
            {
                var existingResp = RespondentService.GetRespondentById(respondent.Id);
                UpdateModel(existingResp);
                RespondentService.SaveRespondent(existingResp);
                added = true;
            }
            if (added)
                return RedirectToAction("Edit", new { id = respondent.Id });
            else return View("New", respondent);
        }

        public ActionResult DeleteRespondent(string id)
        {
            TestService.DeleteTestsByRespondentId(Guid.Parse(id));
            RespondentService.DeleteRespondent(Guid.Parse(id));
            return RedirectToAction("Index");
        }

        public ActionResult DeleteTest(string id)
        {
            string respondentId = TestService.GetTestById(Guid.Parse(id)).RespondentId.ToString();
            TestService.DeleteTest(Guid.Parse(id));
            return RedirectToAction("Edit", new { id = respondentId });
        }

        public ActionResult Edit(string id)
        {
            Respondent respondent = RespondentService.GetRespondentById(Guid.Parse(id));
            RespondentTestsList list = new RespondentTestsList();
            list.Respondent = respondent;
            ExtraInfo info = GetExtraInfo(respondent.Id);
            list.UncompletedTests = info.UnstartedTests;
            list.TestsInProgress = info.TestsInProgress;
            list.UnevaluatedTests = info.UnevaluatedTests;
            var count = TestService.GetByRespondentId(respondent.Id)
                                                .Where(t => t.DateCompleted != null).Count();
            if (count > 0)
                list.Score = TestService.GetByRespondentId(respondent.Id)
                                                    .Where(t => t.DateCompleted != null)
                                                    .Select(t => t.ScorePercent)
                                                    .Sum() / count;
            else
                list.Score = 0;
            list.Tests = new List<Test>();
            list.Tests = TestService.GetByRespondentId(respondent.Id).OrderByDescending(t => t.TestTemplate.Priority).ToList();
            return View(list);
        }

        public ExtraInfo GetExtraInfo(Guid id)
        {
            ExtraInfo info = new ExtraInfo();
            info.UnstartedTests = TestService.GetByRespondentId(id)
                                                .Where(t => t.DateStarted == null && t.DateCompleted == null)
                                                .Count();
            info.TestsInProgress = TestService.GetByRespondentId(id)
                                                .Where(t => t.DateStarted != null && t.DateCompleted == null)
                                                .Count();
            info.UnevaluatedTests = TestService.GetByRespondentId(id)
                                                .Where(t => t.DateCompleted != null && t.DateEvaluated == null)
                                                .Count();

            var count = TestService.GetByRespondentId(id)
                                                .Where(t => t.DateCompleted != null).Count();
            if (count > 0)
                info.Score = TestService.GetByRespondentId(id)
                                                    .Where(t => t.DateCompleted != null)
                                                    .Select(t => t.ScorePercent)
                                                    .Sum() / count;
            else
                info.Score = 0;

            return info;
        }

        public ActionResult AddTest(Guid id)
        {
            RespondentTestTemplateListVM model = new RespondentTestTemplateListVM
            {
                Templates = TemplateService.ListTemplates(),
                RespondentId = id
            };
            return View(model);
        }

        public ActionResult AddTestToRespondent(Guid templateId, Guid respondentId)
        {
            TestTemplate template = TemplateService.GetTemplateById(templateId);

            if (template == null)
                return null;

            Test test = new Test()
            {
                Answers = new List<Answer>(),
                RespondentId = respondentId,
                TestId = template.Id
            };
            
            TestService.AddTest(test);

            return RedirectToAction("Edit", new { id = respondentId });
        }
    }
}

TestDelivery.UI/Controllers/InterviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestDelivery.DAL;
using TestDelivery.ServiceLayer;
using TestDelivery.UI.ViewModels;

namespace TestDelivery.UI.Controllers
{
    public class InterviewController : ApplicationController
    {
        public IRespondentService RespondentService { get; set; }
        public ITestService TestService { get; set; }

        public ActionResult Welcome(string code)
        {
            if (string.IsNullOrWhiteSpace(code))
                return null;

            var respondent = RespondentService.GetRespondentBySecretCode(code.Trim());
            if (respondent == null)
                return null;

            return View(new WelcomeModel
            {
                Respondent = respondent,
                NextTest = TestService.GetNextTestForRespondent(respondent.Id),
                TotalDuration = GetTotalTestDurationForRespondent(respondent.Id)
            });
        }

        private TimeSpan GetTotalTestDurationForRespondent(Guid respondentId)
        {
            return TestService.GetByRespondentId(respondentId)
                         .Where(t => !t.IsComplete)
                         .Select(t => t.TestTemplate.MaxDuration)
                         .Aggregate(new TimeSpan(), (total, duration) => total + duration);
        }

    }
}

TestDelivery.UI/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestDelivery.DAL;
using TestDelivery.ServiceLayer;
using System.Data.Entity;
using System.Data.Objects;
using TestDelivery.UI.Models;
using TestDelivery.UI.ViewModels;
using TestDelivery.DAL.Questions;
using TestDelivery.UI.Helpers;

namespace TestDelivery.UI.Controllers
{

    public class TestController :ApplicationController
    {
        public ITestService TestService { get; set; }
        public IAnswerService AnswerService { get; set; }
        public IQuestionViewService QuestionViewService { get; set; }

        [HttpGet]
        public ActionResult Take(string code)
        {
            Test test = TestService.GetTestBySecretCode(code);
            if (test == null)
                return null;
            return View(test);
        }

        [HttpGet]
        public ActionResult Welcome(string code)
        {
            Test test = TestService.GetTestBySecretCode(code);
            if (test == null)
                return null;

            if (!test.HasStarted)
                return View(test);

            Question question = TestService.GetCurrentQuestion(test);

            return HandleQuestion(test, question);
        }

        private TestQuestionModel GetQuestionModel(Test test, Question question)
        {
            var questionStartTime = test.GetAnswer(question.Id).StartTime;
            var now = DateTime.Now;
            var questionTimePassed = now - questionStartTime.Value;
            var testTimePassed = now - test.DateStarted.Value;

            return new TestQuestionModel
            {
                Question = question,
                TimePassed = Convert.ToInt32(questionTimePassed.TotalSeconds),
                TestTimePassed = Convert.ToInt32(testTimePassed.TotalSeconds),
                TestTimeLimit = test.TestTemplate.TimeLimit,
                QuestionNumber = test.Answers.Count,
                QuestionCount = test.TestTemplate.Questions.Count,
                TestName = test.TestTemplate.Name,
                QuestionViewPath = QuestionViewService.GetTestPartialViewPath(question),
            };
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Next(string code, FormCollection formValues)
        {
            Test test = TestService.GetTestBySecretCode(code);
            if (test == null)
                return null;

            Question question = TestService.GetNextQuestion(test, formValues);
            return HandleQuestion(test, question);
        }

        private ActionResult HandleQuestion(Test test, Question question)
        {
            if (question == null)
            {
                return View("Finish", new FinishTest
                {
                    CurrentTest = test,
                    NextTest = GetNextTest(test)
                });
            }

            return View("Question", GetQuestionModel(test, question));
        }

        private Test GetNextTest(Test test)
        {
            return TestService.GetNextTestForRespondent(test.Respondent.Id);
        }

    }


}

TestDelivery.UI/Views/Respondent/AddTest.cshtml
@model TestDelivery.UI.ViewModels.RespondentVM.RespondentTestTemplateListVM
@{
    ViewBag.Title = "Choose Template";
}

<script type="text/javascript">
    function showAll(id) {
        var val = $(id).is(':checked');
        if (val) {
            $('.container').removeClass('invisible');
        }
        else {
            $('.container').addClass('invisible');
        }
    }
</script>

<style type="text/css">
    .invisible {
        display: none;
    }
</style>

<h2>Choose Template</h2>

Show all templates:
<input type="checkbox" value="0" onchange="showAll(this)" />

<div class="list">
    @foreach (var template in Model.Templates)
    {
        if (template.IsActive)
        {
        <div class="item">
            <a href="@Url.Action("AddTestToRespondent", "Respondent", new { templateId = template.Id, respondentId = Model.RespondentId })" >@template.Name</a>
        </div>
        }
    }
</div>

<div class="list container invisible">
    @foreach (var template in Model.Templates)
    {
         if (!template.IsActive)
        {
        <div class="item">
            <a href="@Url.Action("AddTestToRespondent", "Respondent", new { templateId = template.Id, respondentId = Model.RespondentId })" >@template.Name</a>
        </div>
        }
    }
</div>

TestDelivery.UI/Views/Respondent/Edit.cshtml
@model TestDelivery.UI.ViewModels.RespondentTestsList
@{
    ViewBag.Title = "Edit respondent";
}
@Html.ValidationSummary()
<h3>Extra info</h3>
<div class="item bottom-separator">
    <div class="details">
        @if (Model.UncompletedTests != 0)
        {
            <div class="property">
                Uncompleted Tests: @Model.UncompletedTests
            </div>
        }
        @if (Model.TestsInProgress != 0)
        {
            <div class="property">
                Tests in progress: @Model.TestsInProgress
            </div>
        }
        @if (Model.UnevaluatedTests != 0)
        {
            <div class="property">
                Unevaluated tests: @Model.UnevaluatedTests
            </div>
        }
        <div class="property">
            @if (Model.UnevaluatedTests == 0)
            {<text>Average Score:</text>}
            else
            {<text>Partial score:</text>}
            @Model.Score %
        </div>
    </div>
</div>
@Html.Partial("~/Views/Respondent/Respondent.cshtml", @Model.Respondent)


<div class="editor-label">
    <label for="secretUrl">Interview URL</label>
</div>
<div class="editor-field">
    @{var interviewUrl = Url.Action("Welcome", "Interview", new { code = Model.Respondent.SecretCode }, Request.Url.Scheme);}
    <input id="secretUrl" type="text" value="@interviewUrl"
        disabled="disabled" />
    <div>
        <a href="@interviewUrl" target="_blank">Go to interview
        page</a>
    </div>
</div>


<h3>Tests</h3>
<div class="list">
    @{
        foreach (var test in Model.Tests)
        {                      
        <div class="item bottom-separator">
            <div class="field long">
                <a target="_blank" href="@Url.Action("Evaluate", "EvaluateTest", new { id = test.Id })">@test.TestTemplate.Name</a>
            </div>
            <div class="details">
                <div class="property">
                    Score: @test.ScorePercent %
                </div>
                <a href="@Url.Action("Take", "Test", new { code = test.SecretCode })" target="_blank">
                    Go to test</a>
            </div>
            <div class="field options">
                <button onclick="deleteTest('@test.Id','@test.RespondentId');">Delete</button>
            </div>
        </div>
        }
    }
</div>

<script type="text/javascript">

    function deleteTest(TestId, respondentId) {
        if (confirm("Are you sure?")) {
            var link = '@Url.Action("DeleteTest", "Respondent", new { id = "99999" })'
            link = link.replace("99999", TestId);
            document.location = link;
        }
    }

</script>

<div class="actions">
    <button  onclick="window.location='@Url.Action("AddTest", "Respondent", new { id = Model.Respondent.Id })'">
        Add Test</button>
</div>

TestDelivery.UI/Views/Respondent/Index.cshtml
@model List<TestDelivery.UI.ViewModels.RespondentListItem>
@{
    ViewBag.Title = "Respondents";
}

<h2>Respondents</h2>


<script type="text/javascript">
    function deleteRespondent(id) {
        var conf = confirm("Are you sure you want to delete this respondent? All associated tests will also be deleted");
        if (conf) {
            guid = id;
            link = '@Url.Action("DeleteRespondent", new { id = 999999 })';
            link = link.replace("999999", guid);
            document.location = link;
        }

    }

</script>

<div id="count" class="list" >
    @foreach (var item in Model)
    {
                      
        <div class="item">
            <a target="_self" href="@Url.Action("Edit", "Respondent", new { id = @item.Respondent.Id })">@item.Respondent.Name
                (@item.Respondent.Email)</a>
            <span class="options">
                <button onclick="deleteRespondent('@item.Respondent.Id');">Delete</button>
                 </span>
                <div class="item bottom-separator">
                    <div class="details">
                        <div class="property">
                            @if (item.ExtraInfo.UnevaluatedTests != 0 || item.ExtraInfo.UnstartedTests != 0)
                            {
                                <text>Partial score: </text> 
                            }
                            else{
                                <text>Average score: </text>
                            }
                            @item.ExtraInfo.Score
                        </div>
                        <div class="property">
                            Unstarted Tests: @item.ExtraInfo.UnstartedTests
                        </div>
                        <div class="property">
                            Unevaluated Tests: @item.ExtraInfo.UnevaluatedTests
                        </div>
                        <div class="property">
                            Tests in progress: @item.ExtraInfo.TestsInProgress
                        </div>
                    </div>
                </div>
           
        </div>
         
    }
</div>

<button onclick="document.location='@Url.Action("New")'">Add</button>

TestDelivery.UI/Views/Respondent/New.cshtml
@{
    ViewBag.Title = "Add respondent";
}

@Html.Partial("~/Views/Respondent/Respondent.cshtml")

TestDelivery.UI/Views/Respondent/Respondent.cshtml
@model TestDelivery.DAL.Respondent
@{
    var title = Model.Id == Guid.Empty ? "Add respondent" : "Edit respondent";
}


<h2>@title</h2>


@using (Html.BeginForm("Save", "Respondent"))
{
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.Id)

    <div class="editor-label">
        @Html.LabelFor(m => m.Name, "Respondent name")
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Name)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.Email, "Email")
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Email)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.PhoneNumber, "Phone No")
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.PhoneNumber)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.Url, "Url")
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Url)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.Notes, "Notes")
    </div>
    <div class="editor-field">
        @Html.EditorFor(m => m.Notes)
    </div>
        
    <p>
        <input type="submit" value="Save" />
    </p>

}